worlds:
  enable: true

  server: # These shouldn't change
    ip: 209.240.84.122
    port: 6650

  account: # Change this to a spare (or main?) account's login information
    username: fuwn
    password: somethingsecure22
    avatar: Vamp.mov

discord:
  enable: true

  account:
    token: SoMetOKen22
    app_id: 861756414082678794
    cleanup_app_commands: false

  prefix: m~
